version: '3.2'

services:
    web:
        container_name: ${APP_NAME}_web
        image: nginx:latest
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/app
            - ./docker/8.1/nginx/default.ngx:/etc/nginx/conf.d/default.conf
            - ./docker/8.1/nginx/snippets:/etc/nginx/snippets
        depends_on:
            - php-fpm
            - mysql
        networks:
            - net_ledger
            - net_ledger_front

    php-fpm:
        container_name: ${APP_NAME}_app_back
        hostname: php-fpm
        build:
            context: ./docker/8.1
            dockerfile: app.df
        volumes:
            - ./:/app
        networks:
            - net_ledger

    mysql:
        image: mysql:8
        hostname: ${DB_HOST}
        container_name: ${APP_NAME}_db_main
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
        volumes:
            - ${DB_DATA_FILEPATH}:/var/lib/mysql
        expose:
            - ${DB_PORT}:3306
        networks:
            - net_ledger
networks:
    net_ledger_front:
        external: true
    net_ledger:
        driver: bridge
        name: net_ledger
